#!/usr/bin/env node

'use strict';

var request = require('request');
var Q = require('q');
var moment = require('moment');
var rsj = require('rsj');

require('./db');
var Post = require('mongoose').model('Post');

var config = require('./digestion.json');
var client = require('./cache').client;
var posts = [];

function fetchRedditFeed(subreddit) {
    var deferred = Q.defer();
    var opts = {
        headers: {
            'User-Agent': config.reddit.uaString
        }
    };
    request(config.reddit.url + '/r/' + subreddit + '/hot.json?limit=' + config.reddit.limit, opts, function(error, response, body) {
        if (!error && response.statusCode === 200) {
            var data = JSON.parse(body);
            data.data.children.forEach(function(post) {
                if (post.data.stickied) {
                    return;
                }
                var data = post.data;
                posts.push({
                    'title': data.title,
                    'source': '/r/' + subreddit,
                    'time': moment.utc(data.created_utc * 1000).fromNow(),
                    'link': data.url,
                    'comment_count': data.num_comments,
                    'comment_link': config.reddit.url + data.permalink
                });
            });
            deferred.resolve();
        }
    });
    return deferred.promise;
}

function fetchEchoJsFeed(page) {
    var deferred = Q.defer();
    var start = (page === 1) ? 1 : 33;
    request(config.echojs.url + '/api/getnews/top/' + start + '/' + config.echojs.limit, function(error, response, body) {
        if (!error && response.statusCode === 200) {
            var data = JSON.parse(body);
            data.news.forEach(function(post) {
                posts.push({
                    'title': post.title,
                    'source': config.echojs.source,
                    'time': moment.utc(post.ctime * 1000).fromNow(),
                    'link': post.url,
                    'comment_count': post.comments,
                    'comment_link': config.echojs.url + '/news/' + post.id
                });
            });
            deferred.resolve();
        }
    });
    return deferred.promise;
}

function fetchHackerNewsFeed() {
    var deferred = Q.defer();
    request(config.hackernews.url + '/get/top?limit=' + config.hackernews.limit, function(error, response, body) {
        if (!error && response.statusCode === 200) {
            var data = JSON.parse(body);
            data.stories.forEach(function(post) {
                posts.push({
                    'title': post.title,
                    'source': config.hackernews.source,
                    'time': post.published_time,
                    'link': post.link,
                    'comment_count': post.num_comments,
                    'comment_link': post.comments_link
                });
            });
            deferred.resolve();
        } else {
            deferred.resolve();
        }
    });
    return deferred.promise;
}

function fetchHackADayFeed() {
    var deferred = Q.defer();
    rsj.r2j(config.hackaday.url, function(json) {
        var stories = JSON.parse(json);
        stories.forEach(function(post) {
            // Just to be safe...
            var commentCount = (post['slash:comments'] && post['slash:comments']['#']) || 0;
            posts.push({
                'title': post.title,
                'source': config.hackaday.source,
                'time': moment(post.date).fromNow(),
                'link': post.origlink,
                'comment_count': commentCount,
                'comment_link': post.comments
            });
        });
        deferred.resolve();
    });
    return deferred.promise;
}

function sortPosts() {
    // Algorithm ripped from cjstewart88/sortByTimeAgo (MIT License)
    var sortedPosts = [],
        category,
        separatedPosts = {
            secondsAgo: [],
            minutesAgo: [],
            hoursAgo: [],
            daysAgo: [],
            weeksAgo: [],
            monthsAgo: [],
            yearsAgo: []
        };

    var categories = ['second', 'minute', 'hour', 'day', 'week', 'month', 'year'];
    var length = posts.length;
    for (var i = 0; i < length; i++) {
        var post = posts[i];
        var time = post.time;

        for (var ci = 0; ci < categories.length; ci++) {
            category = categories[ci];
            if (time.indexOf(category) !== -1) {
                separatedPosts[category + 'sAgo'].push(post);
            }
        }
    }
    var sort = function(a, b) {
        var aTime = a.time.match(/\d+/);
        var bTime = b.time.match(/\d+/);
        return parseInt(aTime === null ? 0 : aTime[0]) - parseInt(bTime === null ? 0 : bTime[0]);
    };
    for (category in separatedPosts) {
        separatedPosts[category].sort(sort);
    }


    posts = sortedPosts.concat(separatedPosts.secondsAgo, separatedPosts.minutesAgo, separatedPosts.hoursAgo,
        separatedPosts.daysAgo, separatedPosts.weeksAgo, separatedPosts.monthsAgo,
        separatedPosts.yearsAgo);
}

var deferredList = [];

// Grab Reddit Feeds
config.reddit.subreddits.forEach(function(subreddit) {
    deferredList.push(fetchRedditFeed(subreddit));
});
// Grab EchoJS feed
deferredList.push(fetchEchoJsFeed(1) /* Page 1*/ );
deferredList.push(fetchEchoJsFeed(2) /* Page 2*/ );
// Grab HackerNews feed
deferredList.push(fetchHackerNewsFeed());
// Grab Hack A Day feed
deferredList.push(fetchHackADayFeed());

Q.all(deferredList).then(function() {
    sortPosts();
    // Wipe out DB
    Post.collection.remove({}, function(err) {
        if (!err) {
            console.log('Collection dropped.');

            Post.collection.insert(posts, function(err, docs) {
                if (!err) {
                    console.log('Collection saved! Stored ' + docs.length + ' posts in the DB.');
                    client.flush(function() {
                        console.log('Cache flushed');
                        process.exit(0);
                    });
                } else {
                    console.log('Error saving docs?');
                    process.exit(1);
                }
            });
        } else {
            console.log('Error dropping collection?');
        }
    });
});
